#!/bin/bash
set -o errexit

: ${TERRAFORM_VERSION:=0.6.1}
: ${TMPDIR:=/var/tmp}
: ${PREFIX:=$HOME}

if ! command -v terraform ; then
  cd "${TMPDIR}"
  curl -sSLO "https://dl.bintray.com/mitchellh/terraform/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
  cd "${PREFIX}/bin"
  unzip "${TMPDIR}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
fi
