#!/usr/bin/env bash

set -o errexit

main() {
  if [[ $DEBUG ]] ; then
    set -o xtrace
  fi

  __ensure_chef
  __clone_cookbooks
  __write_node_json
  __write_solo_rb
}

__ensure_chef() {
  mkdir -p /etc/chef

  if command -v chef-solo ; then
    return
  fi

  curl -sL https://www.opscode.com/chef/install.sh | bash
}

__clone_cookbooks() {
  pushd /var/tmp

  rm -rf travis-cookbooks
  git clone https://github.com/travis-ci/travis-cookbooks.git

  rm -rf packer-templates
  git clone https://github.com/travis-infrastructure/packer-templates.git

  popd
}

__write_node_json() {
  cat > /etc/chef/node.json <<EOF
{
  "travis": {
    "worker": {
      "branch": "master",
      "disable_reconfiguration": true
    }
  },
  "travis_internal_base": {
    "opsmatic_disabled": true
  },
  "papertrail": {
    "remote_port": $(cat /var/tmp/papertrail-remote-port || echo 9999)
  },
  "run_list": ["recipe[travis_worker_wrapper]"]
}
EOF
}

__write_solo_rb() {
  cat > /etc/chef/solo.rb <<EOF
cookbook_path %w(
  /var/tmp/packer-templates/cookbooks
  /var/tmp/travis-cookbooks/worker_host
  /var/tmp/travis-cookbooks/ci_environment
)
json_attribs '/etc/chef/node.json'
EOF
}

main "$@"
